name: Checkmarx One Scan
on:
  workflow_dispatch

jobs:
  build:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Checkmarx One CLI Action
        uses: checkmarx/ast-github-action@main #Github Action version
        with:
          project_name: "DevFirstOrg/Hello"
          cx_tenant: ${{ secrets.CX_TENANT_ID }}
          base_uri: ${{ secrets.CX_BASE_URI }} 
          cx_client_id: ${{ secrets.CX_CLIENT_ID }}
          cx_client_secret: ${{ secrets.CX_CLIENT_SECRET }}
          additional_params: "--report-format sarif --output-path ."

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v3
        with: 
          # Path to SARIF file relative to the root of the repository
          sarif_file: cx_result.sarif
